### ISSUE TITLE
extract_data() method gives TypeError: Object of type Date is not JSON serializable

### ISSUE THREAD

**Issue by chrisammon3000** [andreshyer/neo4j-backup#1]
Following the example in [example_extract.py](https://github.com/andreshyer/neo4j-backup/blob/main/example_extract.py), I am encountering an error with Neo4j `Date` types and serialization using Python 3.7.3:
```bash
Exception has occurred: TypeError
Object of type Date is not JSON serializable
  File "/home/bitnami/backup.py", line 19, in <module>
    extractor.extract_data()
```

Full script with secrets removed:
```python
from neo4j import GraphDatabase
from neo4j_backup import Extractor

if __name__ == "__main__":

    uri = "bolt+s://<domain>:7687"
    username = "neo4j"
    password = "<password>"
    # encrypted = False
    # trust = "TRUST_ALL_CERTIFICATES"
    driver = GraphDatabase.driver(uri, auth=(username, password)) #, encrypted=encrypted, trust=trust)

    database = "neo4j"

    project_dir = "data_dump"
    input_yes = False
    compress = True
    extractor = Extractor(project_dir=project_dir, driver=driver, database=database, input_yes=input_yes, compress=compress)
    extractor.extract_data()
```

There is no problem connecting and the progress bar shows everything working until the TypeError gets thrown. I have encountered this before and know of a solution using a custom serializer for Datetimes, so if I can get it to work will submit a pull request later.

**Comment by andreshyer** [comment]
I just pushed a change to the dev branch that should fix the issue with extracting data from nodes with date/time objects in them. Would you be willing to pull the dev branch and make sure that the changes fixed your issue?

When de-bugging, I also noticed that neo4j_importer was not longer working. So, I also pushed a change to fix that as well. But, the change required changing how the data was being saved. So the data that is being extracted will be formatted differently than before. All the node data is being stored separately from the relationship data.
