### ISSUE TITLE
v0.2.0: pip installation does not work

### ISSUE THREAD

**Issue by tiptr** [andreshyer/neo4j-backup#5]
While v0.1.0 works for me, after installing it with pip, the whole package "neo4j_backup" is not found. Under ../site-packages, only the ".dist-info" directory is being created.

Tested with python3.10.

**Comment by andreshyer** [comment]
First time using pyproject.toml, I believe I have fixed the packaging issues in v0.2.2. Would you be willing to verify that v.0.2.2 works for you?

**Comment by tiptr** [comment]
Thank you for your quick response and the great work in general! I just tested your new version. There is a difference: The site-packages directory is now created. Unfortunately it is still created with the wrong name "neo4j-backup" instead of the underscore "_". When I manually change that name, the rest works as expected.

**Comment by tiptr** [comment]
The package-folder inside your "src"-directory is still spelled with the "-", maybe that is the issue?

**Comment by andreshyer** [comment]
I just tried that, it does not seem to fix the issue for some reason. I am wondering if it is because the root directory is neo4j-backup

**Comment by andreshyer** [comment]
You were right, it was the "-" in the src directory, changing the name to "neo4j_backup" worked. I just forgot to run "pip compile" before building. Would you be willing to make sure v0.2.4 works for you? I never would have guess packaging would be this difficult. You have been a huge help, thank you so much!

**Comment by tiptr** [comment]
Now it works, thank you for the quick fix!
