### ISSUE TITLE
Use orjson to fast dump

### ISSUE THREAD

**Issue by vikingUnet** [andreshyer/neo4j-backup#6]
Hello!

Big thanks for this lib, it is really helpful!

I want to use it only as backup/restore solution for community neo4j , 
so fast export/import are very important for me.

Don't you try to use orjson? It is faster and storing a less space on disk.

I changed native json to orjson in local repository of this lib and result very good.

**Comment by andreshyer** [comment]
I have not heard of orjson before, I would be happy to try and implement it. Looking at the library, it definitely seems like they have already solved the problems I have been facing. If you have working code, I would happily merge a pull request. If not, I can try and implement orjson either today or tomorrow.

**Comment by andreshyer** [comment]
Do you know if it compatible with Duration objects as well? I believe that is only property type that is does not support as far I can see.

**Comment by vikingUnet** [comment]
Can you produce some examples with Duration object?

**Comment by andreshyer** [comment]
It appears to be a custom class built by Neo4j, so I would think support might be limited. But the source code for durations can be found at https://github.com/neo4j/neo4j-python-driver/blob/0649f71d97500f52eba1e90faea17ff60f19d6d8/neo4j/time/__init__.py#L336.

Alternatively, durations can be exported in ISO format (strings) https://docs.oracle.com/en/database/oracle/oracle-database/21/adjsn/iso-8601-date-time-and-duration-support.html.

So even if orjson cannot serialize durations, it should still be possible to export durations as ISO strings

**Comment by vikingUnet** [comment]
hm, i have just compared orjson vs native python build-in json without indent and they are equal. In general [indent=4](https://github.com/andreshyer/neo4j-backup/blob/5170de83874b0f67c6ee6fd52b7e4bfc3da691b8/src/neo4j_backup/_backends.py#L8) - is good for reading, but worse for performance: without indent even native json engine shows speedup for 10% and less storage about 70%. Can you raise up indent parameter up to the Extractor constructor to choice - best reading (for small db) or best compact for backups? It will be great)

**Comment by andreshyer** [comment]
I can easily add the indentation as a parameter that the user can modify. 

Thinking about a way to store durations. duration = datetime/time - datetime/time, which is a time object. So durations can be stored as a tuple of (0, duration_time) to signify it is different than a time. That way the property type does not need to be stored along side the properties. 

I should be able to build add the functionality, does not seem that hard to modify. Thank you so much for your input and comments!

**Comment by andreshyer** [comment]
@vikingUnet  Sorry for just now getting back to this. I added in the indentation as the parameter that can be modified, as well as significantly speed up import speeds. 

If you have the time, can you see if the Dev branch works for your needs? I found that using orjson really does not speed up the code that much, or save much disk space on the compressed dump files.
